/*import {
    attribute,
    autoGeneratedHashKey,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('products')
class Product {
    @autoGeneratedHashKey()
    id: string;
    
    @rangeKey()
    createdAt: Date;
    
    @attribute()
    price: string;
    
    @attribute()
    name: string;
}
export { Product }*/